**<font size="4">Numpy Library and Ndarrays</font>**

**Numpy** -> Python data analysis library for dealing with arrays creation and modification. *Ndarrays*, arrays created by numpy library are much more **faster and efficient**, than normal lists and arrays of python, thus used in Data Analysis.

**What is ndarray?**

>N-Dimensional array, indexed by a tuple of positive integers.

**<font size="4">Creating ndarray</font>**

In [22]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
type(a)

numpy.ndarray

**<font size="4">Data types for ndarrays</font>**

In [5]:
a.dtype

dtype('int32')

>It can be of any data type, all 6 (Numbers, String, Set, List, Tuple, Dictionary) which Python have. But, all values in ndarray should be of **same** type.

**<font size="4">Arithmetic with Numpy arrays</font>**

In [7]:
u= np.array([1,0])
v= np.array([3,5])

In [8]:
w=u+v
# addition
x=u-v
# subtraction
y=2*u
# scalar multiplication
z=u*v
# element-wise multiplication

In [9]:
print(w)

[4 5]


In [10]:
print(x)

[-2 -5]


In [11]:
print(y)

[2 0]


In [12]:
print(z)

[3 0]


**<font size="4">Basic Slicing and Indexing</font>**

In [23]:
print(a)

[[1 2 3]
 [4 5 6]]


In [24]:
print(a[:2,:2])
# rows(0,1) and columns(0,1)

[[1 2]
 [4 5]]


In [25]:
print(a[:2,::2])
# rows(0,1) and columns(0,2)(alternate)
# ::2 -> start with 0, end when all iterated once, with steps of 2.

[[1 3]
 [4 6]]


In [27]:
a[0,1]=7
# 0th row, 1st column
print(a)

[[1 7 3]
 [4 5 6]]


>Ndarrays are mutable, unlike strings and tuples.

**<font size="4">Useful Functions of Numpy arrays</font>**

In [28]:
a.dtype
# Data type of array

dtype('int32')

In [29]:
a.size
# Size of array

6

In [30]:
a.ndim
# Dimension of array

2

In [49]:
a.shape
# shape(rows, columns)

(2, 3)

In [32]:
np.dot(u,v)
# Dot product

3

In [33]:
a.mean()
# Mean of the elements 

4.333333333333333

In [34]:
a.max()
# maximum of all elements

7

In [45]:
a.sum()
# sum of all elements

26

In [36]:
x=np.array([0,np.pi/2])
y=np.sin(x)
print(y)
# sin function implementation

[0. 1.]


In [37]:
np.linspace(-2,2,num=5)
# dividing a range into 5 equal parts

array([-2., -1.,  0.,  1.,  2.])

In [50]:
print(a)
print()
print(a.cumsum(axis=1))
# cummulative sum, axis=0 (rows), axis=1 (columns)

[[1 7 3]
 [4 5 6]]

[[ 1  8 11]
 [ 4  9 15]]


In [48]:
np.sqrt(a)
# square root of each element

array([[1.        , 2.64575131, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

**<font size="5">Completed! Thanks.</font>**